/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perfectline.admin;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.HashMap;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author gunebakan
 */
public class MainUi extends javax.swing.JFrame {

    /**
     * Creates new form MainUi
     */
    
    String teamName = "Team1";
    
    
    public MainUi() {
        
        initComponents();        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        //clear Team buttons
        this.quark131.setVisible(false);
        this.quark132.setVisible(false);
        this.quark133.setVisible(false);
        this.quark134.setVisible(false);
        this.quark135.setVisible(false);
        this.quark136.setVisible(false);
        this.quark137.setVisible(false);
        this.quark138.setVisible(false);
        this.quark139.setVisible(false);
        this.quark140.setVisible(false);
        this.quark141.setVisible(false);
        this.quark142.setVisible(false);
        this.quark143.setVisible(false);
        this.quark144.setVisible(false);
        this.quark145.setVisible(false);
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamListPopup = new javax.swing.JPopupMenu();
        teampopupQuarknumber = new javax.swing.JMenuItem();
        talkButton = new javax.swing.JMenuItem();
        removeQuark = new javax.swing.JMenuItem();
        allListPopup = new javax.swing.JPopupMenu();
        allpopupQuarknumber = new javax.swing.JMenuItem();
        talkAll = new javax.swing.JMenuItem();
        addQuark = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AllList = new javax.swing.JPanel();
        quark101 = new javax.swing.JLabel();
        quark102 = new javax.swing.JLabel();
        quark103 = new javax.swing.JLabel();
        quark104 = new javax.swing.JLabel();
        quark105 = new javax.swing.JLabel();
        quark106 = new javax.swing.JLabel();
        quark107 = new javax.swing.JLabel();
        quark108 = new javax.swing.JLabel();
        quark109 = new javax.swing.JLabel();
        quark110 = new javax.swing.JLabel();
        quark111 = new javax.swing.JLabel();
        quark112 = new javax.swing.JLabel();
        quark113 = new javax.swing.JLabel();
        quark114 = new javax.swing.JLabel();
        quark115 = new javax.swing.JLabel();
        TeamList = new javax.swing.JPanel();
        quark131 = new javax.swing.JLabel();
        quark132 = new javax.swing.JLabel();
        quark133 = new javax.swing.JLabel();
        quark134 = new javax.swing.JLabel();
        quark135 = new javax.swing.JLabel();
        quark136 = new javax.swing.JLabel();
        quark137 = new javax.swing.JLabel();
        quark138 = new javax.swing.JLabel();
        quark139 = new javax.swing.JLabel();
        quark140 = new javax.swing.JLabel();
        quark141 = new javax.swing.JLabel();
        quark142 = new javax.swing.JLabel();
        quark143 = new javax.swing.JLabel();
        quark144 = new javax.swing.JLabel();
        quark145 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        teampopupQuarknumber.setText("quarkNumber");
        teampopupQuarknumber.setEnabled(false);
        teamListPopup.add(teampopupQuarknumber);

        talkButton.setText("Özel Konuşma");
        talkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                talkButtonActionPerformed(evt);
            }
        });
        teamListPopup.add(talkButton);

        removeQuark.setText("Takımdan Çıkart");
        removeQuark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeQuarkActionPerformed(evt);
            }
        });
        teamListPopup.add(removeQuark);

        allpopupQuarknumber.setText("quarkNumber");
        allpopupQuarknumber.setEnabled(false);
        allListPopup.add(allpopupQuarknumber);

        talkAll.setText("Özel Konuşma");
        talkAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                talkAllActionPerformed(evt);
            }
        });
        allListPopup.add(talkAll);

        addQuark.setText("Takıma Ekle");
        addQuark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuarkActionPerformed(evt);
            }
        });
        allListPopup.add(addQuark);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PerfectLine Takım Haberleşme Sistemi");
        setPreferredSize(new java.awt.Dimension(940, 600));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Takım Listesi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tüm kullanıcılar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        AllList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        quark101.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark101.setText("101");
        quark101.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark101MouseClicked(evt);
            }
        });
        AllList.add(quark101);

        quark102.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark102.setText("102");
        quark102.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark102MouseClicked(evt);
            }
        });
        AllList.add(quark102);

        quark103.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark103.setText("103");
        quark103.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark103MouseClicked(evt);
            }
        });
        AllList.add(quark103);

        quark104.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark104.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark104.setText("104");
        quark104.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark104MouseClicked(evt);
            }
        });
        AllList.add(quark104);

        quark105.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark105.setText("105");
        quark105.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark105MouseClicked(evt);
            }
        });
        AllList.add(quark105);

        quark106.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark106.setText("106");
        quark106.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark106MouseClicked(evt);
            }
        });
        AllList.add(quark106);

        quark107.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark107.setText("107");
        quark107.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark107MouseClicked(evt);
            }
        });
        AllList.add(quark107);

        quark108.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark108.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark108.setText("108");
        quark108.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark108MouseClicked(evt);
            }
        });
        AllList.add(quark108);

        quark109.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark109.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark109.setText("109");
        quark109.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark109MouseClicked(evt);
            }
        });
        AllList.add(quark109);

        quark110.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark110.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark110.setText("110");
        quark110.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark110MouseClicked(evt);
            }
        });
        AllList.add(quark110);

        quark111.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark111.setText("111");
        quark111.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark111MouseClicked(evt);
            }
        });
        AllList.add(quark111);

        quark112.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark112.setText("112");
        quark112.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark112MouseClicked(evt);
            }
        });
        AllList.add(quark112);

        quark113.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark113.setText("113");
        quark113.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark113MouseClicked(evt);
            }
        });
        AllList.add(quark113);

        quark114.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark114.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark114.setText("114");
        quark114.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark114MouseClicked(evt);
            }
        });
        AllList.add(quark114);

        quark115.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark115.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark115.setText("115");
        quark115.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark115MouseClicked(evt);
            }
        });
        AllList.add(quark115);

        getContentPane().add(AllList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 290, 420));

        TeamList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        quark131.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark131.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark131.setText("101");
        quark131.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark131MouseClicked(evt);
            }
        });
        TeamList.add(quark131);

        quark132.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark132.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark132.setText("102");
        quark132.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark132MouseClicked(evt);
            }
        });
        TeamList.add(quark132);

        quark133.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark133.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark133.setText("103");
        quark133.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark133MouseClicked(evt);
            }
        });
        TeamList.add(quark133);

        quark134.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark134.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark134.setText("104");
        quark134.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark134MouseClicked(evt);
            }
        });
        TeamList.add(quark134);

        quark135.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark135.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark135.setText("105");
        quark135.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark135MouseClicked(evt);
            }
        });
        TeamList.add(quark135);

        quark136.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark136.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark136.setText("106");
        quark136.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark136MouseClicked(evt);
            }
        });
        TeamList.add(quark136);

        quark137.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark137.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark137.setText("107");
        quark137.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark137MouseClicked(evt);
            }
        });
        TeamList.add(quark137);

        quark138.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark138.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark138.setText("108");
        quark138.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark138MouseClicked(evt);
            }
        });
        TeamList.add(quark138);

        quark139.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark139.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark139.setText("109");
        quark139.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark139MouseClicked(evt);
            }
        });
        TeamList.add(quark139);

        quark140.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark140.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark140.setText("110");
        quark140.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark140MouseClicked(evt);
            }
        });
        TeamList.add(quark140);

        quark141.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark141.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark141.setText("111");
        quark141.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark141MouseClicked(evt);
            }
        });
        TeamList.add(quark141);

        quark142.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark142.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark142.setText("112");
        quark142.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark142MouseClicked(evt);
            }
        });
        TeamList.add(quark142);

        quark143.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark143.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark143.setText("113");
        quark143.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark143MouseClicked(evt);
            }
        });
        TeamList.add(quark143);

        quark144.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark144.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark144.setText("114");
        quark144.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark144MouseClicked(evt);
            }
        });
        TeamList.add(quark144);

        quark145.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quark145.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/walkie-talkie.png"))); // NOI18N
        quark145.setText("115");
        quark145.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quark145MouseClicked(evt);
            }
        });
        TeamList.add(quark145);

        getContentPane().add(TeamList, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 290, 420));

        jMenu1.setText("Dosya");

        jMenuItem3.setText("Çıkış");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Yardım");

        jMenuItem1.setText("Hakkında");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                    
        JOptionPane.showMessageDialog(new JFrame(), "PerfectLine Takım iletişim Yazılımı. 2016", "Hakkında",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void quark102MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark102MouseClicked
        
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("102");
            this.teamListPopup.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_quark102MouseClicked

    private void quark107MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark107MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("107");
            this.teamListPopup.setVisible(true);
            
        }
        
    }//GEN-LAST:event_quark107MouseClicked

    private void quark112MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark112MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("112");
            this.teamListPopup.setVisible(true);
            
        }
        
    }//GEN-LAST:event_quark112MouseClicked

    private void quark132MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark132MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("103");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark132MouseClicked

    private void quark137MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark137MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("107");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark137MouseClicked

    private void quark142MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark142MouseClicked
       if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("112");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark142MouseClicked

    private void quark101MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark101MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("101");
            this.teamListPopup.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_quark101MouseClicked

    private void quark103MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark103MouseClicked
        if(evt.getButton() == 3){
            this.allListPopup.setLocation(evt.getLocationOnScreen());
            this.allpopupQuarknumber.setText("103");
            this.allListPopup.setVisible(true);
            
        }
        
    }//GEN-LAST:event_quark103MouseClicked

    private void quark104MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark104MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("104");
            this.teamListPopup.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_quark104MouseClicked

    private void quark105MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark105MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("105");
            this.teamListPopup.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_quark105MouseClicked

    private void quark106MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark106MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("106");
            this.teamListPopup.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_quark106MouseClicked

    private void quark108MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark108MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("108");
            this.teamListPopup.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_quark108MouseClicked

    private void quark110MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark110MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("110");
            this.teamListPopup.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_quark110MouseClicked

    private void quark109MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark109MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("109");
            this.teamListPopup.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_quark109MouseClicked

    private void quark111MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark111MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("111");
            this.teamListPopup.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_quark111MouseClicked

    private void quark113MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark113MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("113");
            this.teamListPopup.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_quark113MouseClicked

    private void quark114MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark114MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("114");
            this.teamListPopup.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_quark114MouseClicked

    private void quark115MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark115MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("115");
            this.teamListPopup.setVisible(true);
            
        }
       
        
    }//GEN-LAST:event_quark115MouseClicked
       
    private void quark133MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark133MouseClicked
        
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("103");
            this.teamListPopup.setVisible(true);
            
        }
        
    }//GEN-LAST:event_quark133MouseClicked

    private void talkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_talkButtonActionPerformed
        System.out.println("talking with team member");
    }//GEN-LAST:event_talkButtonActionPerformed

    private void removeQuarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeQuarkActionPerformed
       
        Client client = new Client(Integer.parseInt(this.teampopupQuarknumber.getText()));
  
        if(client.Channelcommand("remove-channel", teamName)){
        
            removefromTeam(Integer.parseInt(this.teampopupQuarknumber.getText()));
            
        }else{                    
            JOptionPane.showMessageDialog(new JFrame(), "Kablosuz Cihaza Bağlanılamıyor!", "Hata!",JOptionPane.ERROR_MESSAGE);        
        }
        this.teamListPopup.setVisible(false);
          
    }//GEN-LAST:event_removeQuarkActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.teamListPopup.setVisible(false);
        this.allListPopup.setVisible(false);
    }//GEN-LAST:event_formMouseClicked

    private void talkAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_talkAllActionPerformed
        System.out.println("talking with non team member");
    }//GEN-LAST:event_talkAllActionPerformed

    private void addQuarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuarkActionPerformed
        Client client = new Client(Integer.parseInt(this.allpopupQuarknumber.getText()));
        if(client.Channelcommand("add-channel", teamName)){
            addtoTeam(Integer.parseInt(this.allpopupQuarknumber.getText()));
        }else{
            JOptionPane.showMessageDialog(new JFrame(), "Kablosuz Cihaza Bağlanılamıyor!", "Hata!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addQuarkActionPerformed

    private void quark131MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark131MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("101");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark131MouseClicked

    private void quark134MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark134MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("104");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark134MouseClicked

    private void quark135MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark135MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("105");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark135MouseClicked

    private void quark136MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark136MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("106");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark136MouseClicked

    private void quark138MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark138MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("108");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark138MouseClicked

    private void quark139MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark139MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("109");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark139MouseClicked

    private void quark140MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark140MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("110");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark140MouseClicked

    private void quark141MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark141MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("111");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark141MouseClicked

    private void quark143MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark143MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("113");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark143MouseClicked

    private void quark144MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark144MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("114");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark144MouseClicked

    private void quark145MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quark145MouseClicked
        if(evt.getButton() == 3){
            this.teamListPopup.setLocation(evt.getLocationOnScreen());
            this.teampopupQuarknumber.setText("115");
            this.teamListPopup.setVisible(true);
            
        }
    }//GEN-LAST:event_quark145MouseClicked

private void addtoTeam(int quarkId){
    //Its idiot code i have ever write
    
    switch (quarkId) {
            case 101:  
                quark101.setVisible(false);
                quark131.setVisible(true);
            break;
            case 102:  
                quark102.setVisible(false);
                quark132.setVisible(true);
            break;
            case 103:  
                quark103.setVisible(false);
                quark133.setVisible(true);
            break;
            case 104:  
                quark104.setVisible(false);
                quark134.setVisible(true);
            break;
            case 105:  
                quark105.setVisible(false);
                quark135.setVisible(true);
            break;
            case 106:  
                quark106.setVisible(false);
                quark136.setVisible(true);
            break;
            case 107:  
                quark107.setVisible(false);
                quark137.setVisible(true);
            break;
            case 108:  
                quark108.setVisible(false);
                quark138.setVisible(true);
            break;
            case 109:  
                quark109.setVisible(false);
                quark139.setVisible(true);
            break;
            case 110:  
                quark110.setVisible(false);
                quark140.setVisible(true);
            break;    
            case 111:  
                quark111.setVisible(false);
                quark141.setVisible(true);
            break;
            case 112:  
                quark112.setVisible(false);
                quark142.setVisible(true);
            break;
            case 113:  
                quark113.setVisible(false);
                quark143.setVisible(true);
            break;
            case 114:  
                quark114.setVisible(false);
                quark144.setVisible(true);
            break;
            case 115:  
                quark115.setVisible(false);
                quark145.setVisible(true);
            break;
    }
    
}
private void removefromTeam(int quarkId){
    //Its idiot code i have ever write
    
    switch (quarkId) {
            case 101:  
                quark101.setVisible(true);
                quark131.setVisible(false);
            break;
            case 102:  
                quark102.setVisible(true);
                quark132.setVisible(false);
            break;
            case 103:  
                quark103.setVisible(true);
                quark133.setVisible(false);
            break;
            case 104:  
                quark104.setVisible(true);
                quark134.setVisible(false);
            break;
            case 105:  
                quark105.setVisible(true);
                quark135.setVisible(false);
            break;
            case 106:  
                quark106.setVisible(true);
                quark136.setVisible(false);
            break;
            case 107:  
                quark107.setVisible(true);
                quark137.setVisible(false);
            break;
            case 108:  
                quark108.setVisible(true);
                quark138.setVisible(false);
            break;
            case 109:  
                quark109.setVisible(true);
                quark139.setVisible(false);
            break;
            case 110:  
                quark110.setVisible(true);
                quark140.setVisible(false);
            break;    
            case 111:  
                quark111.setVisible(true);
                quark141.setVisible(false);
            break;
            case 112:  
                quark112.setVisible(true);
                quark142.setVisible(false);
            break;
            case 113:  
                quark113.setVisible(true);
                quark143.setVisible(false);
            break;
            case 114:  
                quark114.setVisible(true);
                quark144.setVisible(false);
            break;
            case 115:  
                quark115.setVisible(true);
                quark145.setVisible(false);
            break;
    }
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AllList;
    private javax.swing.JPanel TeamList;
    private javax.swing.JMenuItem addQuark;
    private javax.swing.JPopupMenu allListPopup;
    private javax.swing.JMenuItem allpopupQuarknumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel quark101;
    private javax.swing.JLabel quark102;
    private javax.swing.JLabel quark103;
    private javax.swing.JLabel quark104;
    private javax.swing.JLabel quark105;
    private javax.swing.JLabel quark106;
    private javax.swing.JLabel quark107;
    private javax.swing.JLabel quark108;
    private javax.swing.JLabel quark109;
    private javax.swing.JLabel quark110;
    private javax.swing.JLabel quark111;
    private javax.swing.JLabel quark112;
    private javax.swing.JLabel quark113;
    private javax.swing.JLabel quark114;
    private javax.swing.JLabel quark115;
    private javax.swing.JLabel quark131;
    private javax.swing.JLabel quark132;
    private javax.swing.JLabel quark133;
    private javax.swing.JLabel quark134;
    private javax.swing.JLabel quark135;
    private javax.swing.JLabel quark136;
    private javax.swing.JLabel quark137;
    private javax.swing.JLabel quark138;
    private javax.swing.JLabel quark139;
    private javax.swing.JLabel quark140;
    private javax.swing.JLabel quark141;
    private javax.swing.JLabel quark142;
    private javax.swing.JLabel quark143;
    private javax.swing.JLabel quark144;
    private javax.swing.JLabel quark145;
    private javax.swing.JMenuItem removeQuark;
    private javax.swing.JMenuItem talkAll;
    private javax.swing.JMenuItem talkButton;
    private javax.swing.JPopupMenu teamListPopup;
    private javax.swing.JMenuItem teampopupQuarknumber;
    // End of variables declaration//GEN-END:variables
}
